{
 "title": "Golden Metrics Dashboard",
 "panels": [
  {
   "title": "Taxa de Requisições por Segundo (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Taxa de Erro (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{http_status=~\"5..\"}[5m])) / sum(rate(http_server_requests_total[5m])) * 100"
    }
   ]
  },
  {
   "title": "Latência P99 (segundos)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}